language: php

jobs:
  include:
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install -n

script:
  - vendor/bin/phpunit ./tests/